# Generated by Django 4.2.2 on 2023-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Analise', 'Em análise'), ('Aprovada', 'Aprovada'), ('Negada', 'Negada')], default='Analise', max_length=128, verbose_name='Status')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Empréstimo Pretendido')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
            },
        ),
    ]
